### ISSUE TITLE
Crashes in debug mode.

### ISSUE THREAD

**Issue by legnaleurc** [ettoolong/BBSFox-E10S#29]
```
0x00007ffff2cdc9fe in nsSocketTransport::InitiateSocket (this=this@entry=0x7fffd4c9ac00) at /home/wcpan/local/src/firefox/netwerk/base/nsSocketTransport2.cpp:1258
1258                MOZ_CRASH("Attempting to connect to non-local address!");
```

```
#0  0x00007ffff2cdc9fe in nsSocketTransport::InitiateSocket() (this=this@entry=0x7fffd4c9ac00) at /home/wcpan/local/src/firefox/netwerk/base/nsSocketTransport2.cpp:1258
#1  0x00007ffff2cdd6e3 in nsSocketTransport::OnSocketEvent(unsigned int, nsresult, nsISupports*) (this=0x7fffd4c9ac00, type=<optimized out>, status=nsresult::NS_OK, param=0x7fffc320fa40)
    at /home/wcpan/local/src/firefox/netwerk/base/nsSocketTransport2.cpp:1861
#2  0x00007ffff2ce11d1 in nsSocketEvent::Run() (this=<optimized out>) at /home/wcpan/local/src/firefox/netwerk/base/nsSocketTransport2.cpp:85
#3  0x00007ffff2c1731f in nsThread::ProcessNextEvent(bool, bool*) (this=0x7fffe7405600, aMayWait=<optimized out>, aResult=0x7fffe2afe7ef)
    at /home/wcpan/local/src/firefox/xpcom/threads/nsThread.cpp:989
#4  0x00007ffff2c40d04 in NS_ProcessNextEvent(nsIThread*, bool) (aThread=0x7fffe7405600, aMayWait=<optimized out>) at /home/wcpan/local/src/firefox/xpcom/glue/nsThreadUtils.cpp:290
#5  0x00007ffff2cdbab0 in nsSocketTransportService::Run() (this=0x7fffe69e4290) at /home/wcpan/local/src/firefox/netwerk/base/nsSocketTransportService2.cpp:943
#6  0x00007ffff2c1731f in nsThread::ProcessNextEvent(bool, bool*) (this=0x7fffe7405600, aMayWait=<optimized out>, aResult=0x7fffe2afe99f)
    at /home/wcpan/local/src/firefox/xpcom/threads/nsThread.cpp:989
#7  0x00007ffff2c40d04 in NS_ProcessNextEvent(nsIThread*, bool) (aThread=0x7fffe7405600, aMayWait=<optimized out>) at /home/wcpan/local/src/firefox/xpcom/glue/nsThreadUtils.cpp:290
#8  0x00007ffff302efcf in mozilla::ipc::MessagePumpForNonMainThreads::Run(base::MessagePump::Delegate*) (this=0x7fffe5c7da40, aDelegate=0x7fffe74ad690)
    at /home/wcpan/local/src/firefox/ipc/glue/MessagePump.cpp:340
#9  0x00007ffff2fedcbb in MessageLoop::RunInternal() (this=0x7fffe74ad690) at /home/wcpan/local/src/firefox/ipc/chromium/src/base/message_loop.cc:233
#10 0x00007ffff2fede0d in MessageLoop::Run() (this=<optimized out>) at /home/wcpan/local/src/firefox/ipc/chromium/src/base/message_loop.cc:226
#11 0x00007ffff2fede0d in MessageLoop::Run() (this=this@entry=0x7fffe74ad690) at /home/wcpan/local/src/firefox/ipc/chromium/src/base/message_loop.cc:206
#12 0x00007ffff2c15c4d in nsThread::ThreadFunc(void*) (aArg=0x7fffe7405600) at /home/wcpan/local/src/firefox/xpcom/threads/nsThread.cpp:391
#13 0x00007ffff7fbd7be in _pt_root (arg=0x7fffe7479340) at /home/wcpan/local/src/firefox/nsprpub/pr/src/pthreads/ptthread.c:216
#14 0x00007ffff7bc5454 in start_thread (arg=0x7fffe2aff700) at pthread_create.c:334
#15 0x00007ffff11b1eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by ettoolong** [comment]
於 5.0.18 版修正
